# Generated by Django 6.0.2 on 2026-02-16 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_is_deleted'),
        ('shops', '0002_remove_shop_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='shops.shop'),
        ),
    ]
