# Generated by Django 6.0.2 on 2026-02-16 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='employee',
        ),
    ]
